import {
  Activity,
  Brain,
  Briefcase,
  Building2,
  Camera,
  Cpu,
  Gavel,
  HeartPulse,
  LineChart,
  Megaphone,
  MousePointerClick,
  Palette,
  Pill,
  Rocket,
  Scale,
  Shield,
  Smile,
  Stethoscope,
  TrafficCone,
  Users,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  doctor: Stethoscope,
  surgeon: HeartPulse,
  pharmacist: Pill,
  dentist: Smile,
  "software-engineer": Cpu,
  "ai-engineer": Brain,
  "cybersecurity-analyst": Shield,
  "civil-engineer": TrafficCone,
  entrepreneur: Rocket,
  "marketing-manager": Megaphone,
  "financial-analyst": LineChart,
  "business-manager": Briefcase,
  lawyer: Scale,
  psychologist: Brain,
  "social-worker": Users,
  judge: Gavel,
  "graphic-designer": Palette,
  "ux-designer": MousePointerClick,
  architect: Building2,
  "content-creator": Camera,
};

export const careerIcon = (id: string): LucideIcon => map[id] ?? Activity;
