/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ResultsCareerIdRouteImport } from './routes/results.$careerId'
import { Route as SimulationsIndexRouteImport } from './routes/simulations.index'
import { Route as SimulationsCareerIdRouteImport } from './routes/simulations.$careerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsCareerIdRoute = ResultsCareerIdRouteImport.update({
  id: '/results/$careerId',
  path: '/results/$careerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsIndexRoute = SimulationsIndexRouteImport.update({
  id: '/simulations/',
  path: '/simulations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsCareerIdRoute = SimulationsCareerIdRouteImport.update({
  id: '/simulations/$careerId',
  path: '/simulations/$careerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/results/$careerId': typeof ResultsCareerIdRoute
  '/simulations/$careerId': typeof SimulationsCareerIdRoute
  '/simulations/': typeof SimulationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/results/$careerId': typeof ResultsCareerIdRoute
  '/simulations/$careerId': typeof SimulationsCareerIdRoute
  '/simulations': typeof SimulationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/results/$careerId': typeof ResultsCareerIdRoute
  '/simulations/$careerId': typeof SimulationsCareerIdRoute
  '/simulations/': typeof SimulationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/results/$careerId'
    | '/simulations/$careerId'
    | '/simulations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/results/$careerId'
    | '/simulations/$careerId'
    | '/simulations'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/results/$careerId'
    | '/simulations/$careerId'
    | '/simulations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  ResultsCareerIdRoute: typeof ResultsCareerIdRoute
  SimulationsCareerIdRoute: typeof SimulationsCareerIdRoute
  SimulationsIndexRoute: typeof SimulationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$careerId': {
      id: '/results/$careerId'
      path: '/results/$careerId'
      fullPath: '/results/$careerId'
      preLoaderRoute: typeof ResultsCareerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/': {
      id: '/simulations/'
      path: '/simulations'
      fullPath: '/simulations/'
      preLoaderRoute: typeof SimulationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/$careerId': {
      id: '/simulations/$careerId'
      path: '/simulations/$careerId'
      fullPath: '/simulations/$careerId'
      preLoaderRoute: typeof SimulationsCareerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  ResultsCareerIdRoute: ResultsCareerIdRoute,
  SimulationsCareerIdRoute: SimulationsCareerIdRoute,
  SimulationsIndexRoute: SimulationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
